### ISSUE TITLE
Dump is not working

### ISSUE THREAD

**Issue by ichsanbahri91** [r0oth3x49/ghauri#14]
i have been trying to dump database, tablle but is not showing anything

**Comment by r0oth3x49** [comment]
It should work but I will check again..

**Comment by r0oth3x49** [comment]
What type of SQLi? Boolean , time or error.
What is back end DBMS identified?

**Comment by ichsanbahri91** [comment]
time base sqlmap , im trying with this command sqlmap -u "bla bla" --technique = T -D bla bla -T bla blaa --dump

**Comment by ichsanbahri91** [comment]
so, we can dump entire database now right?

**Comment by r0oth3x49** [comment]
Yes it should. I hope the issue is resolved of extracting wrong characters

**Comment by ichsanbahri91** [comment]
still not working, iam trying using using command -D "databasename" -T "table" --dump stil not working output still [21:48:22] [INFO] testing MySQL
[21:48:22] [INFO] confirming MySQL
[21:48:22] [INFO] the back-end DBMS is MySQL

but if um dump only selected columns , it work

this tool cannot dump entire database or table ?

**Comment by r0oth3x49** [comment]
@ichsanbahri91 added the support please git pull the latest version it should work now.
